<?php

use App\Http\Controllers\UserController;
use App\Models\User;
use Illuminate\Foundation\Application;
use Illuminate\Support\Facades\Route;
use Inertia\Inertia;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// ROUTES GENERATED BY INERTIA
Route::get('/', function () {
    return Inertia::render('Welcome', [
        'canLogin' => Route::has('login'),
        'canRegister' => Route::has('register'),
        'laravelVersion' => Application::VERSION,
        'phpVersion' => PHP_VERSION,
    ]);
});

Route::middleware([
    'auth:sanctum',
    config('jetstream.auth_session'),
    'verified',
])->group(function () {
    Route::get('/dashboard', function () {
        return Inertia::render('Dashboard');
    })->name('dashboard');
});


// Route::middleware([
//     'auth:sanctum',
//     config('jetstream.auth_session'),
//     'verified',
// ])->group(function () {
//     Route::get('/user', function () {

//         $users = User::all();

//         return Inertia::render('User', compact('users'));
//     })->name('user.index');
// });


Route::group(['middleware' => ['auth:sanctum',config('jetstream.auth_session'),'verified',], 'prefix' => 'dashboard'],function(){
    Route::resource('user',UserController::class)->parameters(['user' => 'customer']);
    Route::delete('user/avatar/delete/{customer}',[UserController::class,'deleteAvatar'])->name('user.deleteAvatar');
});
    





// Route::middleware(['auth:sanctum',config('jetstream.auth_session'),'verified',])->delete('/dashboard/user/avatar/delete/{customer}',[UserController::class,'deleteAvatar']);